apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wuek85wce-java-springboot
  janus-idp.io/tekton: wuek85wce-java-springboot
  backstage.io/kubernetes-id: wuek85wce-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wuek85wce-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
